apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-controller
  namespace: knative-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-controller
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: yolo-controller
    spec:
      serviceAccountName: controller
      containers:
      - name: yolo
        image: scaling-demo
        ports:
        - name: metrics
          containerPort: 9090
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
      volumes:
        - name: config-logging
          configMap:
            name: config-logging
