apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-controller
  namespace: knative-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-controller
  template:
    metadata:
      labels:
        app: app-controller
    spec:
      serviceAccountName: controller
      containers:
      - name: app
        image: scaling-demo
